### ISSUE TITLE
Hardware Ref

### ISSUE THREAD

**Issue by algo1980** [bbc/dvbcss-synctiming#7]
Hi,
Can someone suggest me a a dvbc hardware solution. 
thanks

**Comment by matt-hammond-001** [comment]
Hello,

I don't fully understand the question. This project's hardware and software should work for any system that implements the DVB CSS protocols.

kind regards

Matt

**Comment by algo1980** [comment]
Hi matt,
regards for your reply. But what hardware do you suggest firmware should be built upon. If aiming for 4k. In addition it have to be cost effective too. I have been looking into some chips from st and broadcoam, but a little confused.

**Comment by matt-hammond-001** [comment]
The [README](https://github.com/bbc/dvbcss-synctiming/blob/master/hardware/README.md) in the [/hardware](https://github.com/bbc/dvbcss-synctiming/tree/master/hardware) subdirectory of this project gives full details of what hardware is needed to build the calibration/measurement system. This is resolution independent and is not based around a TV or STB chipset.

Is your question actually about implementation of DVB CSS / HbbTV 2 in a TV/STB? This is technically outside the scope of this github project, however you are welcome to contact me directly be email (see bottom of [README](https://github.com/bbc/dvbcss-synctiming/blob/master/README.md)).

**Comment by algo1980** [comment]
hi matt this is a very basic and far away from what i am wanting for this project. I wonder if arduini due is capable of delivering good results. I am going through the read me but cant see a way to contact you matt.
Regards.

**Comment by matt-hammond-001** [comment]
Hello. Contact details are at the bottom of the main README. See the heading "Contact and discuss".

Regarding the suitability of the arduino: we have built and used this system and can therefore confirm from experience that it works. In practice we have been able to make measurements that are accurate to within a few milliseconds.

**Comment by algo1980** [comment]
I can't find contact link in read me.
Can u please send me the link. 

Thank you

**Comment by matt-hammond-001** [comment]
The email addresses are not provided as links. This is done to avoid spam. The names of the "original authors" near the end of the [README](https://github.com/bbc/dvbcss-synctiming/blob/master/README.md) can be translated into email addresses.

**Comment by algo1980** [comment]
invain i tried to contact but no replies from the admins.

**Comment by matt-hammond-001** [comment]
I don't understand - nobody in this project is described as an "admin".

Matt 'dot' Hammond 'at' bbc.co.uk

**Comment by matt-hammond-001** [comment]
Closing this issue as the conversation appears to have ended
